trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'chudinov'
  imageName: 'nginx-hello'

steps:
- script:
    displayName: 'docker build'
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .    

- script:
    displayName: 'docker push'    
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)        