trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'chudinov'
  imageName: 'nginx-hello'
  pswd: 'Merlons11'
  XXX: $(XXX)

steps:
- script: docker build -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'Docker build'
- script: |
    echo XXX---
    echo "$(XXX)"
    echo "$XXX"
    echo "${XXX}"
    echo '${XXX}'
    echo $XXX
    echo $XXX1
    echo $(dockerPassword)
    echo $pswd
    echo YYY---
    docker login --username $(dockerId) --password $(pswd)
    docker push $(dockerId)/$(imageName)
  displayName: 'Docker push'
  env:
    pswd: $(dockerPassword)
    XXX1: $(XXX)