trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'chudinov'
  imageName: 'nginx-hello'

steps:
- script: docker build -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'docker build'

- script: |
    docker login --username $(dockerId) --password $pswd
    docker push $(dockerId)/$(imageName)
  displayName: 'docker push'
  env:
    pswd: $(dockerPassword)
    