trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'chudinov'
  imageName: 'nginx-hello'
  pswd1: 'Merlons11'
  XXX1: $(XXX)
  pswd3: $(dockerPassword)

steps:
- script: docker build -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'Docker build'
- script: |
    echo XXX---
    echo "$(pswd3)"
    echo "$pswd3"
    echo "${pswd3}"
    echo '${pswd3}'
    echo $pswd3
    echo YYY---
    docker login --username $(dockerId) --password $(pswd)
    docker push $(dockerId)/$(imageName)
  displayName: 'Docker push'
  env:
    pswd2: $(dockerPassword)
    XXX2: $(XXX)